PRICES = {
    "candy": 2.5,
    "pastry": 1.5,
    "chips": 2,
    "el_sabroso": 2,
    "combos": 3,
    "soups": 2,
    "island_snacks" : 3,
    "SF_seeds":2.25,
    "pop_tarts" : 1.5,
    "takis" : 2.25,
    "fruit_snacks" : 1.25,
    "fruit_cups" : 2.5,
    "gum": 1.25,
    "g_bar": 3,
    "nesquick": 3 , 
    "red_bull": 4.75,
    "gatorade": 3,
    "monster" : 4,
    "mnt_dew": 3.5,
    "water" : 2.25,
    "soda": 2,
    "arizona" : 1.25,
    "v8": 2.25,
    "langers": 2,
    "star_bucks":4.75,
    "bang" : 3,
    "electrolit" : 4.75,
    "coconut_water" : 3.5,
    "5_hour" : 3.25,
    "breakfast":3.75,
    "burrito" : 3.25,
    "xl_burrito": 4,
    "calzone": 4,
    "big_chicken": 4.5,
    "pbj": 1.5,
    "brats": 3,
    "F_&_R": 6.25,
    "tuna": 3.5,
    "parfait" : 6.25,
    "ciggs" : 10,
    "grizzly": 6,
    "stokers": 18,
    "lighters" : 2,
    "chapstick": 3.25,
}