PRICES = {
    "candy": 2.5,
    "pastry": 1.5,
    "chips": 2,
    "el sabroso": 2,
    "combos": 3,
    "soups": 2,
    "island snacks" : 3,
    "sun flower seeds":2.25,
    "pop tarts" : 1.5,
    "takis" : 2.25,
    "fruit snacks" : 1.25,
    "gum": 1.25,
    "gatorade bars": 3,
    "nesquick": 3 , 
    "red bull": 4.75,
    "gatorade": 3,
    "monster" : 4,
    "brisk": 2.5,
    "water" : 2.25,
    "soda": 2,
    "Arizona's" : 1.25,
    "v8": 2.25,
    "langers": 2,
    "body armor" : 3,
    "starbucks":4.75,
    "raze" : 3,
    "bang" : 3,
    "electro life" : 4.75,
    "cocounut water" : 3.5,
    "5 hour" : 3.75,
    "breakfast":3.75,
    "small burrito" : 3.25,
    "large burrito": 4,
    "calzone": 4,
    "big chicken": 4.5,
    "pbj": 1.5,
    "brats": 3,
    "fresh & ready": 6.25,
    "tuna": 3.5,
    "parfait" : 6.25,
    "ciggs" : 10,
    "grizzly": 6,
    "stokers": 18,
    "lighters" : 2,
    "chapstick": 3.25,
    "log": 30,
}