#:kivy 1.10.0

<MyScreenManager>:

    MenuScreen:
        id: menu_screen
    DrinksScreen:
        id: drinks_screen
    RetailScreen:
        id: retail_screen
    FoodScreen:
        id: food_screen
    RecieptScreen:
        id: reciept_screen
    SixthScreen:
        id: sixth_screen
    SnacksScreen:
        id: snacks_screen
    Start_Count_Screen:
        id: start_count_screen

<ImageButton>:
    text: ' '
    pos: self.pos
    size: self.size
    font_size: '12dp'